### ISSUE TITLE
Use PredefinedRetryPolicies instead of magic value

### ISSUE THREAD

**Issue by tobywf** [aws-cloudformation/aws-cloudformation-resource-providers-logs#10]
[PredefinedRetryPolicies.getDefaultRetryPolicy()](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/retry/PredefinedRetryPolicies.html#getDefaultRetryPolicy--) here:

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs/blob/9705c4b3a0322de53a3b3b6f6dce332153dd3634/aws-logs-metricfilter/src/main/java/com/aws/logs/metricfilter/ClientBuilder.java#L11

**Comment by miparnisari** [comment]
Not applicable anymore.
