### ISSUE TITLE
LogGroup: incorrect resource schema

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/aws-cloudformation-resource-providers-logs#34]
Current properties according to the schema:

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs/blob/3dcd55b8e95cc76ccf9f2fb64318f0b2bbbd5547/aws-logs-loggroup/aws-logs-loggroup.json#L6-L39

But according to the [service API](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_CreateLogGroup.html#API_CreateLogGroup_RequestParameters), `CreateLogGroup` also accepts:

- kmsKeyId
- tags

**Comment by PatMyron** [comment]
more accurately genuine CloudFormation coverage gaps than an incorrect resource schema:
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/77
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/128
