### ISSUE TITLE
High latency of MetricFilter

### ISSUE THREAD

**Issue by wbingli** [aws-cloudformation/aws-cloudformation-resource-providers-logs#39]
The MetricFilter has much higher latency, it seems the call chain make an unnecessary stabilization, but this resource needs no stabilization.

 The default stabilization delay is 5 seconds,  we should remove such 5 seconds unnecessary latency.

**Comment by miparnisari** [comment]
> The MetricFilter has much higher latency,

Can you provide data to back this claim?

**Comment by miparnisari** [comment]
> The default stabilization delay is 5 seconds, we should remove such 5 seconds unnecessary latency.

https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/18f61798eb8b99d564f06657733604154e3e0f64/src/main/java/software/amazon/cloudformation/proxy/CallChain.java#L400-L402

**Comment by ammokhov** [comment]
closing this as been fixed by #47
