### ISSUE TITLE
AWS::Logs::MetricFilter does not have a Unit property

### ISSUE THREAD

**Issue by macdonaldezra** [aws-cloudformation/aws-cloudformation-resource-providers-logs#66]
The optional Unit property of a MetricFilter can be specified when manually creating the filter, but there is no way to specify it in CloudFormation for the MetricFilter. 

I found that Terraform also supports this attribute in their [CloudWatch Log Metric Filter resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_metric_filter#unit) and am wondering if CloudFormation would support doing the same. Otherwise, if this attribute is not a priority, could I get some clarification as to why?

**Comment by waifa** [comment]
Units feature was added and can now be used as part of MetricFilters in CloudFormation.
