### ISSUE TITLE
 Fail and return NotFound error code on Delete

### ISSUE THREAD

**Issue by aygold92** [aws-cloudformation/aws-cloudformation-resource-providers-logs#8]
[The Handler Contract](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html) states that we should fail and return `NotFound` on Delete, and then the Client should ignore this error. This is to provide consistency across different implementations

**Comment by miparnisari** [comment]
@aygold92 is this about the LogGroup type? Because if so, this is already here:

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs/blob/3dcd55b8e95cc76ccf9f2fb64318f0b2bbbd5547/aws-logs-loggroup/src/main/java/software/amazon/logs/loggroup/DeleteHandler.java#L25

**Comment by aygold92** [comment]
not sure the history of this but it appears to be resolved
